import { Controller, Get, Query, ValidationPipe } from '@nestjs/common';
import { AnalyzePredictionDto } from './dto/analyze-prediction.dto';
import { AnalyzeSharkProbabilityUseCase } from './usecases/analyze-shark-probability.usecase';

@Controller('openai')
export class OpenAIController {
  constructor(private readonly analyze: AnalyzeSharkProbabilityUseCase) {}

  /**
   * Returns HTML generated by OpenAI analysis.
   * Images should be obtained directly from NASA routes.
   * Maintains response contract intact.
   */
  @Get('analyze')
  async analyzeRoute(
    @Query(new ValidationPipe({ transform: true })) dto: AnalyzePredictionDto,
  ): Promise<{ html: string }> {
    const wmsOptions = dto.toWmsOptions();
    const result = await this.analyze.execute(
      dto.time,
      dto.regionHint,
      wmsOptions,
    );

    return {
      html: result.html,
    };
  }
}
