services:
  - type: web
    name: sharks-from-space-api
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      # HTTP
      - key: HTTP_TIMEOUT_MS
        value: 10000
      - key: HTTP_RETRY
        value: 2
      # NASA
      - key: NASA_WMS_BASE
        value: https://gibs.earthdata.nasa.gov/wms/epsg4326/best/wms.cgi
      - key: NASA_WMS_VERSION
        value: 1.3.0
      - key: NASA_WMS_CRS
        value: EPSG:4326
      - key: NASA_LAYER_CHLA
        value: OCI_PACE_Chlorophyll_a
      - key: NASA_LAYER_SST
        value: GHRSST_L4_MUR_Sea_Surface_Temperature
      - key: NASA_DEFAULT_FORMAT
        value: image/png
      # OPENAI - Configure estas no dashboard por segurança
      - key: OPENAI_API_KEY
        sync: false  # Será configurado manualmente no dashboard
      - key: OPENAI_MODEL
        value: gpt-4o
      - key: OPENAI_BASE_URL
        value: https://api.openai.com/v1
      - key: OPENAI_ASSISTANT_ID
        sync: false  # Será configurado manualmente no dashboard
